web/router.ex
defmodule Blog.Router do
  use Blog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Blog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/articles", ArticleController do
      resources "/comments", CommentController, only: [:create, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blog do
  #   pipe_through :api
  # end
end

lib/blog/endpoint.ex
defmodule Blog.Endpoint do
  use Phoenix.Endpoint, otp_app: :blog

  socket "/socket", Blog.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :blog, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_blog_key",
    signing_salt: "1Da9cGoi"

  plug Blog.Router
end

lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo, otp_app: :blog
end

web/models/article.ex
defmodule Blog.Article do
  use Blog.Web, :model

  schema "articles" do
    field :title, :string
    field :text, :string
    has_many :comments, Blog.Comment, on_delete: :delete_all

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :text])
    |> validate_required([:title, :text])
    |> validate_length(:title, min: 5)
  end
end

web/models/comment.ex
defmodule Blog.Comment do
  use Blog.Web, :model

  schema "comments" do
    field :commenter, :string
    field :body, :string
    belongs_to :article, Blog.Article

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:commenter, :body, :article_id])
    |> validate_required([:commenter, :body, :article_id])
  end
end

web/controllers/article_controller.ex
defmodule Blog.ArticleController do
  use Blog.Web, :controller
  alias Blog.Article
  alias Blog.Comment

  def index(conn, _params) do
    articles = Repo.all(Article)
    render conn, "index.html", articles: articles
  end

  def show(conn, %{"id" => id}) do
    article = Repo.get(Article, id) |> Repo.preload([:comments])
    changeset = Comment.changeset(%Comment{})
    render conn, "show.html", article: article, changeset: changeset
  end

  def new(conn, _params) do
    changeset = Article.changeset(%Article{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"article" => article_params}) do
    changeset = Article.changeset(%Article{}, article_params)
    case Repo.insert(changeset) do
      {:ok, article} ->
        conn
        |> put_flash(:info, "Article created")
        |> redirect(to: article_path(conn, :show, article))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  def edit(conn, %{"id" => id}) do
    article = Repo.get(Article, id)
    changeset = Article.changeset(article)
    render conn, "edit.html", article: article, changeset: changeset
  end

  def update(conn, %{"id" => id, "article" => article_params}) do
    article = Repo.get(Article, id)
    changeset = Article.changeset(article, article_params)
    case Repo.update(changeset) do
      {:ok, article} ->
        conn
        |> put_flash(:info, "Article updated")
        |> redirect(to: article_path(conn, :show, article))
      {:error, changeset} ->
        render conn, "edit.html", article: article, changeset: changeset
    end
  end

  def delete(conn, %{"id" => id}) do
    article = Repo.get(Article, id)

    # use ! because it should always work, otherwise raise an error
    Repo.delete!(article)
    conn
    |> put_flash(:info, "Article deleted")
    |> redirect(to: article_path(conn, :index))

  end

end

web/controllers/comment_controller.ex
defmodule Blog.CommentController do
  use Blog.Web, :controller
  alias Blog.Comment
  alias Blog.Article

  plug :scrub_params, "comment" when action in [:create] # convert require params from "" to nil

  def create(conn, %{"article_id" => article_id, "comment" => comment_params}) do
    changeset = Comment.changeset(%Comment{}, Map.put(comment_params, "article_id", article_id))
    article = Article |> Repo.get(article_id) |> Repo.preload([:comments])

    if changeset.valid? do
      Repo.insert(changeset)
      conn
      |> put_flash(:info, "Comment added.")
      |> redirect(to: article_path(conn, :show, article))
    else
      {:error, changeset} = Repo.insert(changeset) # to show beautifull error info
      render(conn, Blog.ArticleView, "show.html", article: article, changeset: changeset)
    end
  end

  def delete(conn, %{"article_id" => article_id, "id" => id}) do
    article = Repo.get(Article, article_id)
    comment = Repo.get(Comment, id)
    Repo.delete!(comment)
    conn
    |> put_flash(:info, "Comment deleted!")
    |> redirect(to: article_path(conn, :show, article))
  end
end

web/controllers/page_controller.ex
defmodule Blog.PageController do
  use Blog.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/articel_view.ex
defmodule Blog.ArticleView do
  use Blog.Web, :view
end

web/views/comment_view.ex
defmodule Blog.CommentView do
  use Blog.Web, :view
end

web/views/error_view.ex
defmodule Blog.ErrorView do
  use Blog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Blog.LayoutView do
  use Blog.Web, :view
end

web/views/page_view.ex
defmodule Blog.PageView do
  use Blog.Web, :view
end

web/templates/article/comment.html.eex
<p>
<strong>Commenter:</strong>
<%= @comment.commenter %>
</p>

<p>
<strong>Comment:</strong>
<%= @comment.body %>
</p>

<p>
<%= link "Delete Comment", to: article_comment_path(@conn, :delete, @article, @comment), method: :delete, data: [confirm: "Are you sure?"] %>
</p>

web/templates/article/comment_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<div class="form-group">
  <%= label f, :commenter, class: "control-label" %>
  <%= text_input f, :commenter, class: "form-control" %>
  <%= error_tag f, :commenter %>
</div>

<div class="form-group">
  <%= label f, :body, class: "control-label" %>
  <%= textarea f, :body, class: "form-control" %>
  <%= error_tag f, :body %>
</div>

<%= submit "Submit", class: "btn btn-primary" %>
<% end %>

web/templates/article/edit.html.eex
<h1>Edit Article</h1>
<%= render "form.html", changeset: @changeset, action: article_path(@conn, :update, @article) %>
<%= link "Back", to: article_path(@conn, :index) %>

web/templates/article/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
  <div class="form-group">
    <%= label f, :text, class: "control-label" %>
    <%= text_input f, :text, class: "form-control" %>
    <%= error_tag f, :text %>
  </div>
  <%= submit "Submit", class: "btn btn-primary" %>
<% end %>

web/templates/article/index.html.eex
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <%= for article <- @articles do %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link("Show", to: article_path(@conn, :show, article)) %></td>
    <td><%= link("Edit", to: article_path(@conn, :edit, article)) %></td>
    <td><%= link("Delete", to: article_path(@conn, :delete, article), method: :delete, data: [confirm: "Are you suer?"]) %></td>
  </tr>
  <% end %>
</table>

<%= link "New article", to: article_path(@conn, :new) %>

web/templates/article/new.html.eex
<h1>New Article</h1>
<%= render "form.html", changeset: @changeset, action: article_path(@conn, :create) %>
<%= link "Back", to: article_path(@conn, :index) %>

web/templates/article/show.html.eex
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>

<h2>Comments</h2>
<%= for comment <- @article.comments do %>
  <%= render "comment.html", conn: @conn, comment: comment, article: @article %>
<% end %>

<h2>Add a comment:</h2>
<%= render "comment_form.html", article: @article, changeset: @changeset, action: article_comment_path(@conn, :create, @article) %>

<%= link "Edit", to: article_path(@conn, :edit, @article) %> |
<%= link "Back", to: article_path(@conn, :index) %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Blog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
  <%= link "My blog", to: article_path(@conn, :index) %>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>